function f = make_table1_conventional_with_ic()
% TABLE 1 — conventional model parameter and initial-condition table.
%
% Columns:
%   Parameter / initial condition | Description | Value / range | Source / status
%
% The table contains only quantities that are normally reported in a
% mathematical-modelling parameter table:
%   1) fixed / estimated model parameters and time-varying functions;
%   2) the initial value of every model compartment.
%
% Policy-effect definitions, admissibility criteria and ensemble-size
% summaries are intentionally excluded from Table 1.
%
% IMPORTANT provenance:
%   - N1 and N2 are population data.
%   - c_i(t), q_i(t), m_i(t), d_i(t), and beta are inferred by the UDE.
%   - gamma and mu are fixed, not estimated.
%   - the compartment initial values are fixed model initialization values;
%     they are not trainable UDE parameters in the final v6 implementation.
%   - C1(0)=C2(0)=0 is a definition of the cumulative record at the start
%     of the analysis window, not an epidemiological estimate.

d = mr.load_data();

headers = { ...
    'Parameter / initial condition', ...
    'Description', ...
    'Value / range', ...
    'Source / status'};

%% ------------------------------------------------------------------------
% Frozen manuscript values
% -------------------------------------------------------------------------
N1 = double(d.populations(1));
N2 = double(d.populations(2));

beta  = double(d.baseline.beta);
gamma = double(d.baseline.gamma);
mu    = double(d.baseline.mu);

bounds = double(d.bounds);
beta_bounds = double(d.beta_bounds);

% Fixed order in the manuscript snapshot:
% [c1,c2,q1,q2,m1,m2,d1,d2]
c_bounds = bounds(1,:);
q_bounds = bounds(3,:);
m_bounds = bounds(5,:);
d_bounds = bounds(7,:);

% Baseline state order:
% [S1,S2,Sq1,Sq2,I1,I2,Iq1,Iq2,R1,R2,C1,C2]
x0 = double(d.baseline.states(1,:));

S10  = x0(1);
S20  = x0(2);
Sq10 = x0(3);
Sq20 = x0(4);
I10  = x0(5);
I20  = x0(6);
Iq10 = x0(7);
Iq20 = x0(8);
R10  = x0(9);
R20  = x0(10);
C10  = x0(11);
C20  = x0(12);

%% ------------------------------------------------------------------------
% Conventional four-column table
% -------------------------------------------------------------------------
rows = cell(21,4);

% ===== Model parameters =====
rows(1,:) = { ...
    'tex:N_1', ...
    'Population of Guangdong', ...
    sprintf('%.0f',N1), ...
    'Population data [1]'};

rows(2,:) = { ...
    'tex:N_2', ...
    'Population of Guangxi', ...
    sprintf('%.0f',N2), ...
    'Population data [2]'};

rows(3,:) = { ...
    'tex:c_i(t)', ...
    'Effective contact rate in region i', ...
    sprintf('tex:[%.0f, %.0f]~day^{-1}',c_bounds(1),c_bounds(2)), ...
    'Estimated time-varying function (UDE)'};

rows(4,:) = { ...
    'tex:q_i(t)', ...
    'Quarantine / isolation fraction in region i', ...
    sprintf('tex:[%.0f, %.0f]',q_bounds(1),q_bounds(2)), ...
    'Estimated time-varying function (UDE)'};

rows(5,:) = { ...
    'tex:m_i(t)', ...
    'Cross-regional mixing fraction from region i', ...
    sprintf('tex:[%.1f, %.1f]',m_bounds(1),m_bounds(2)), ...
    'Estimated time-varying function (UDE)'};

rows(6,:) = { ...
    'tex:d_i(t)', ...
    'Movement rate of non-quarantined infected individuals from region i', ...
    sprintf('tex:[%.1f, %.1f]~day^{-1}',d_bounds(1),d_bounds(2)), ...
    'Estimated time-varying function (UDE)'};

rows(7,:) = { ...
    'tex:\beta', ...
    'Transmission probability per effective contact', ...
    sprintf('%.8f (bounds %.3f--%.2f)',beta,beta_bounds(1),beta_bounds(2)), ...
    'Estimated constant (UDE)'};

rows(8,:) = { ...
    'tex:\gamma', ...
    'Recovery rate of infected individuals', ...
    'tex:1/7~day^{-1}', ...
    'Fixed from literature [3]'};

rows(9,:) = { ...
    'tex:\mu', ...
    'Release rate of quarantined susceptible individuals', ...
    'tex:1/7~day^{-1}', ...
    'Fixed model assumption (mean 7 d)'};

% ===== Initial conditions =====
rows(10,:) = { ...
    'tex:S_1(0)', ...
    'Initial susceptible population in Guangdong', ...
    sprintf('%.0f',S10), ...
    'Derived from N_1 and fixed initial states'};

rows(11,:) = { ...
    'tex:S_2(0)', ...
    'Initial susceptible population in Guangxi', ...
    sprintf('%.0f',S20), ...
    'Derived from N_2 and fixed initial states'};

rows(12,:) = { ...
    'tex:S_1^q(0)', ...
    'Initial quarantined susceptible population in Guangdong', ...
    sprintf('%.0f',Sq10), ...
    'Fixed initialization (model assumption)'};

rows(13,:) = { ...
    'tex:S_2^q(0)', ...
    'Initial quarantined susceptible population in Guangxi', ...
    sprintf('%.0f',Sq20), ...
    'Fixed initialization (model assumption)'};

rows(14,:) = { ...
    'tex:I_1(0)', ...
    'Initial unquarantined infected population in Guangdong', ...
    sprintf('%.0f',I10), ...
    'Fixed initialization (model assumption)'};

rows(15,:) = { ...
    'tex:I_2(0)', ...
    'Initial unquarantined infected population in Guangxi', ...
    sprintf('%.0f',I20), ...
    'Fixed initialization (model assumption)'};

rows(16,:) = { ...
    'tex:I_1^q(0)', ...
    'Initial quarantined infected population in Guangdong', ...
    sprintf('%.0f',Iq10), ...
    'Fixed initialization (model assumption)'};

rows(17,:) = { ...
    'tex:I_2^q(0)', ...
    'Initial quarantined infected population in Guangxi', ...
    sprintf('%.0f',Iq20), ...
    'Fixed initialization (model assumption)'};

rows(18,:) = { ...
    'tex:R_1(0)', ...
    'Initial removed population in Guangdong', ...
    sprintf('%.0f',R10), ...
    'Fixed initialization (model assumption)'};

rows(19,:) = { ...
    'tex:R_2(0)', ...
    'Initial removed population in Guangxi', ...
    sprintf('%.0f',R20), ...
    'Fixed initialization (model assumption)'};

rows(20,:) = { ...
    'tex:C_1(0)', ...
    'Initial cumulative reported-case recorder in Guangdong', ...
    sprintf('%.0f',C10), ...
    'Defined as zero at start of analysis window'};

rows(21,:) = { ...
    'tex:C_2(0)', ...
    'Initial cumulative reported-case recorder in Guangxi', ...
    sprintf('%.0f',C20), ...
    'Defined as zero at start of analysis window'};

%% ------------------------------------------------------------------------
% Integrity checks against the frozen current model
% -------------------------------------------------------------------------
if abs(gamma - 1/7) > 1e-12
    error('Table1:GammaMismatch', ...
        'Expected gamma = 1/7, found %.12g.',gamma);
end

if abs(mu - 1/7) > 1e-12
    error('Table1:MuMismatch', ...
        'Expected mu = 1/7, found %.12g.',mu);
end

if abs(beta - 0.092208199203) > 1e-10
    warning('Table1:BetaChanged', ...
        'Current baseline beta is %.12g; the loaded value will be displayed.',beta);
end

expected_x0 = [ ...
    127000000, ...
    50369995, ...
    0, ...
    4, ...
    0, ...
    1, ...
    0, ...
    0, ...
    0, ...
    0, ...
    0, ...
    0];

if max(abs(x0-expected_x0)) > 1e-8
    warning('Table1:InitialStateChanged', ...
        'The loaded initial state differs from the current manuscript reference; loaded values will be displayed.');
end

%% ------------------------------------------------------------------------
% Render
% -------------------------------------------------------------------------
% Four columns only, with wider Description and Source columns.
f = mr.tablefigure( ...
    'Table1', ...
    headers, ...
    rows, ...
    [.15 .39 .20 .26], ...
    6.8, ...
    11.2);

f.UserData.ManuscriptTable = rows;

f.UserData.SourceNotes = { ...
    '[1] Guangdong Provincial Bureau of Statistics (2023), 2022 Guangdong population statistics.'; ...
    '[2] Guangxi Zhuang Autonomous Region Bureau of Statistics (2023), 2022 Guangxi population statistics.'; ...
    '[3] Biala TA, Afolabi YO, Khaliq AQM. How efficient is contact tracing in mitigating the spread of COVID-19? A mathematical modeling approach. Applied Mathematical Modelling. 2022;103:714-730. doi:10.1016/j.apm.2021.11.011.'};

mr.save(f,'Table1','tables');

end
