%% plot_fig5_final_corrected.m
% Directly runnable MATLAB R2024b script.
%
% FINAL CORRECTED FIG. 5
% ------------------------------------------------------------
% This script uses the THREE frozen manuscript ensembles stored
% losslessly in MainResults/matlab/data/main_results.mat:
%
%   d.run30   -> analysis_runs/main_30
%   d.run50   -> analysis_runs/sensitivity_50
%   d.run100  -> analysis_runs/sensitivity_100
%
% IMPORTANT:
%   d.rankings(:,:,1:3) are NOT N=30/50/100.
%   They are the N=100 ranking matrices for:
%       (:,:,1) total reported
%       (:,:,2) GD reported
%       (:,:,3) GX reported
%
% Therefore all ensemble-size comparisons below are reconstructed directly
% from d.run30.values, d.run50.values, and d.run100.values.
%
% Panels:
%   a  N=100 total-reported pairwise ranking matrix
%   b  All 36 unordered pairs: robustness at N=30/50/100
%   c  N=100 effect separation and ranking consistency (aligned lollipops)
%   d  Nested-ensemble sensitivity of four decision-relevant criteria
%
% Outputs:
%   <current working directory>\Fig5\Fig5_a.fig/.png
%   <current working directory>\Fig5\Fig5_b.fig/.png
%   <current working directory>\Fig5\Fig5_c.fig/.png
%   <current working directory>\Fig5\Fig5_d.fig/.png

clearvars;
close all;
clc;

%% ------------------------------------------------------------------------
% Load frozen manuscript snapshot
% -------------------------------------------------------------------------
d = mr.load_data();
s = mr.style();

sizes = [30 50 100];

r30  = d.run30;
r50  = d.run50;
r100 = d.run100;

if size(r30.values,1) ~= 30 || size(r50.values,1) ~= 50 || size(r100.values,1) ~= 100
    error('Fig5:RunSizeMismatch', ...
        'Expected run30/run50/run100 to contain 30/50/100 members.');
end

if isstring(d.strategies)
    strategyNames = cellstr(d.strategies(:));
elseif iscell(d.strategies)
    strategyNames = d.strategies(:);
else
    strategyNames = cellstr(string(d.strategies(:)));
end

nStrategies = numel(strategyNames);

if nStrategies ~= 9
    error('Fig5:StrategyCount','Expected 9 strategies, found %d.',nStrategies);
end

%% ------------------------------------------------------------------------
% Reconstruct the THREE total-reported ranking matrices correctly
% -------------------------------------------------------------------------
R30  = pairwise_total_reported_local(r30.values);
R50  = pairwise_total_reported_local(r50.values);
R100 = pairwise_total_reported_local(r100.values);

rankByN = cat(3,R30,R50,R100);

% The saved d.rankings object is N=100 total/GD/GX, NOT 30/50/100.
% Verify that its first slice matches our independently reconstructed
% N=100 total-reported matrix exactly.
savedTotal100 = double(d.rankings(:,:,1));

if max(abs(savedTotal100(:)-R100(:))) > 1e-12
    error('Fig5:RankingMismatch', ...
        'Reconstructed N=100 total-reported ranking matrix differs from d.rankings(:,:,1).');
end

%% ------------------------------------------------------------------------
% Build all 36 unordered pair summaries
% -------------------------------------------------------------------------
nPairs = nStrategies*(nStrategies-1)/2;

pairI = zeros(nPairs,1);
pairJ = zeros(nPairs,1);
pairLabels = cell(nPairs,1);
robustness = zeros(nPairs,3);
medianDelta100 = zeros(nPairs,1);
medianAbsEffect100 = zeros(nPairs,1);

E100 = squeeze(r100.values(:,:,1,5))/1000;  % total reported, 10^3 cases

q = 0;

for i = 1:(nStrategies-1)
    for j = (i+1):nStrategies

        q = q + 1;

        pairI(q) = i;
        pairJ(q) = j;
        pairLabels{q} = [strategyNames{i} '-' strategyNames{j}];

        for kk = 1:3
            p = rankByN(i,j,kk);
            robustness(q,kk) = max(p,1-p);
        end

        delta100 = E100(:,i)-E100(:,j);

        medianDelta100(q) = median(delta100,'omitnan');
        medianAbsEffect100(q) = abs(medianDelta100(q));
    end
end

%% ------------------------------------------------------------------------
% Hard integrity checks for the manuscript's frozen main findings
% -------------------------------------------------------------------------
unanimousCounts = zeros(1,3);

for kk = 1:3
    unanimousCounts(kk) = count_unanimous_pairs_local(rankByN(:,:,kk));
end

if ~isequal(unanimousCounts,[6 6 4])
    error('Fig5:UnanimousCountMismatch', ...
        'Expected unanimous pair counts [6 6 4], found [%d %d %d].', ...
        unanimousCounts(1),unanimousCounts(2),unanimousCounts(3));
end

hhllCounts = [ ...
    sum(r30.values(:,6,1,5)  > r30.values(:,9,1,5)), ...
    sum(r50.values(:,6,1,5)  > r50.values(:,9,1,5)), ...
    sum(r100.values(:,6,1,5) > r100.values(:,9,1,5))];

if ~isequal(hhllCounts,[30 50 100])
    error('Fig5:HHLLMismatch', ...
        'Expected HH > LL counts [30 50 100], found [%d %d %d].', ...
        hhllCounts(1),hhllCounts(2),hhllCounts(3));
end

pairs100 = unanimous_pair_labels_local(R100,strategyNames);
expectedPairs100 = sort({'NN-LL','NH-LL','HH-LL','LH-LL'});

if ~isequal(sort(pairs100),expectedPairs100)
    error('Fig5:UnanimousPairIdentityMismatch', ...
        'The N=100 unanimous strategy pairs do not match the frozen manuscript result.');
end

% Cross-check the three existing robustness summaries against the frozen
% expected_robustness object in main_results.mat.
reportedCounts = zeros(11,3);

for kk = 1:3
    n = sizes(kk);
    reportedCounts(:,kk) = mr.robustness(d,n,1);

    if ~isequal(reportedCounts(:,kk),d.expected_robustness(:,kk,1))
        error('Fig5:RobustnessMismatch', ...
            'mr.robustness(d,%d,1) differs from expected_robustness.',n);
    end
end

%% ------------------------------------------------------------------------
% Four selected sensitivity criteria for panel d
% -------------------------------------------------------------------------
criterionNames = { ...
    'HH > LL', ...
    'LL harms both regions', ...
    'HH win-win', ...
    'Unanimously ordered pairs'};

criterionFrac = zeros(4,3);

for kk = 1:3

    n = sizes(kk);

    criterionFrac(1,kk) = reportedCounts(1,kk)/n;
    criterionFrac(2,kk) = reportedCounts(3,kk)/n;
    criterionFrac(3,kk) = reportedCounts(4,kk)/n;
    criterionFrac(4,kk) = unanimousCounts(kk)/36;
end

%% ------------------------------------------------------------------------
% Shared style
% -------------------------------------------------------------------------
INK      = [0.08 0.13 0.17];
SUBINK   = [0.35 0.39 0.42];
GRIDC    = [0.82 0.84 0.85];

if isfield(s,'benefit')
    TEAL = s.benefit;
else
    TEAL = [0.10 0.60 0.63];
end

if isfield(s,'navy')
    NAVY = s.navy;
else
    NAVY = [0.10 0.27 0.43];
end

if isfield(s,'harm')
    HARM = s.harm;
else
    HARM = [0.80 0.58 0.25];
end

SLATE = [0.48 0.60 0.69];

OTHER = darken_local(HARM,0.10);
UNAN  = darken_local(TEAL,0.06);
BEST  = darken_local(NAVY,0.02);

%% ------------------------------------------------------------------------
% Output folder
% -------------------------------------------------------------------------
output_dir = fullfile(pwd,'Fig5');

if ~exist(output_dir,'dir')
    mkdir(output_dir);
end

%% =========================================================================
% PANEL a — N=100 total-reported pairwise ranking matrix
% =========================================================================
figA = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[100 40 1050 960], ...
    'Name','Fig5_a', ...
    'NumberTitle','off');

set(figA,'Renderer','painters');

annotation(figA,'textbox',[0.020 0.945 0.040 0.040], ...
    'String','a', ...
    'EdgeColor','none', ...
    'FontName','Arial', ...
    'FontSize',30, ...
    'FontWeight','bold', ...
    'Color','k');

axA = axes(figA,'Position',[0.155 0.215 0.625 0.650]);

imagesc(axA,R100);
axis(axA,'image');

colormap(axA,s.fraction);
clim(axA,[0 1]);

set(axA, ...
    'YDir','reverse', ...
    'FontName','Arial', ...
    'FontSize',16, ...
    'LineWidth',1.0, ...
    'TickDir','out', ...
    'Box','off', ...
    'XColor',INK, ...
    'YColor',INK);

xticks(axA,1:nStrategies);
xticklabels(axA,strategyNames);
xtickangle(axA,90);

yticks(axA,1:nStrategies);
yticklabels(axA,strategyNames);

xlabel(axA,'Strategy B','FontSize',19,'Color',INK);
ylabel(axA,'Strategy A','FontSize',19,'Color',INK);

hold(axA,'on');

for i = 1:nStrategies
    for j = 1:nStrategies

        val = R100(i,j);

        if val > 0.65
            txtColor = [1 1 1];
        else
            txtColor = INK;
        end

        text(axA,j,i,sprintf('%d',round(100*val)), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontName','Arial', ...
            'FontSize',16.2, ...
            'Color',txtColor);

        if i ~= j && (val <= 1e-12 || val >= 1-1e-12)
            rectangle(axA, ...
                'Position',[j-0.48 i-0.48 0.96 0.96], ...
                'EdgeColor',NAVY, ...
                'LineWidth',1.45);
        end
    end
end

annotation(figA,'textbox',[0.18 0.895 0.58 0.030], ...
    'String','Cell value = fraction of the 100-solution ensemble in which strategy A yields fewer reported cases than strategy B', ...
    'EdgeColor','none', ...
    'HorizontalAlignment','center', ...
    'FontName','Arial', ...
    'FontSize',13.0, ...
    'Color',SUBINK);

cbA = colorbar(axA,'southoutside');
cbA.Position = [0.195 0.115 0.545 0.020];
cbA.Ticks = [0 0.5 1];
cbA.TickLabels = {'0','0.5','1'};
cbA.FontName = 'Arial';
cbA.FontSize = 12;
cbA.Color = INK;
cbA.Label.String = 'Fraction with A fewer cases than B';
cbA.Label.FontSize = 14;
cbA.Label.Color = INK;

save_panel_local(figA,output_dir,'Fig5_a');

%% =========================================================================
% PANEL b — robustness across the N=30,50,100 frozen ensembles
% =========================================================================
% Sort by N=100 robustness, then N=50, then N=30.
sortKey = [-robustness(:,3), -robustness(:,2), -robustness(:,1)];
[~,ordB] = sortrows(sortKey,[1 2 3]);

pairLabels_B = pairLabels(ordB);
robustness_B = robustness(ordB,:);

figB = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[110 25 1300 1340], ...
    'Name','Fig5_b', ...
    'NumberTitle','off');

set(figB,'Renderer','painters');

annotation(figB,'textbox',[0.020 0.956 0.040 0.035], ...
    'String','b', ...
    'EdgeColor','none', ...
    'FontName','Arial', ...
    'FontSize',30, ...
    'FontWeight','bold', ...
    'Color','k');

axB = axes(figB,'Position',[0.235 0.085 0.720 0.835]);
hold(axB,'on');

for r = 1:nPairs

    if robustness_B(r,3) >= 1-1e-12
        patch(axB,[0.495 1.005 1.005 0.495], ...
            [r-0.42 r-0.42 r+0.42 r+0.42], ...
            [0.91 0.96 0.96], ...
            'FaceAlpha',0.9, ...
            'EdgeColor','none', ...
            'HandleVisibility','off');
    end
end

xline(axB,0.50,':','Color',[0.76 0.76 0.76],'LineWidth',1.0);
xline(axB,1.00,'-','Color',[0.40 0.40 0.40],'LineWidth',1.1);

for r = 1:nPairs

    rr = robustness_B(r,:);
    rmin = min(rr);
    rmax = max(rr);

    if rr(3) >= 1-1e-12
        barCol = TEAL;
    elseif rr(3) >= 0.90
        barCol = NAVY;
    elseif rr(3) >= 0.75
        barCol = SLATE;
    else
        barCol = [0.63 0.69 0.74];
    end

    plot(axB,[0.50 1.00],[r r],'-', ...
        'Color',[0.88 0.89 0.90], ...
        'LineWidth',7.4, ...
        'Clipping','off');

    plot(axB,[rmin rmax],[r r],'-', ...
        'Color',barCol, ...
        'LineWidth',7.4, ...
        'Clipping','off');

    plot(axB,[rmin rmax],[r r],'-', ...
        'Color','k', ...
        'LineWidth',1.0, ...
        'Clipping','off');

    plot(axB,rr(1),r,'o', ...
        'MarkerSize',7.0, ...
        'MarkerFaceColor','w', ...
        'MarkerEdgeColor','k', ...
        'LineWidth',1.0);

    plot(axB,rr(2),r,'d', ...
        'MarkerSize',7.8, ...
        'MarkerFaceColor',HARM, ...
        'MarkerEdgeColor','k', ...
        'LineWidth',0.9);

    plot(axB,rr(3),r,'o', ...
        'MarkerSize',8.8, ...
        'MarkerFaceColor',barCol, ...
        'MarkerEdgeColor','k', ...
        'LineWidth',0.9);
end

set(axB, ...
    'YDir','reverse', ...
    'YLim',[0.35 nPairs+0.65], ...
    'YTick',1:nPairs, ...
    'YTickLabel',pairLabels_B, ...
    'XLim',[0.49 1.015], ...
    'XTick',[0.50 0.60 0.70 0.80 0.90 1.00], ...
    'FontName','Arial', ...
    'FontSize',11.0, ...
    'LineWidth',1.0, ...
    'TickDir','out', ...
    'Box','off', ...
    'XColor',INK, ...
    'YColor',INK);

xlabel(axB,'Ranking consistency across admissible solutions', ...
    'FontSize',19.0, ...
    'Color',INK);

annotation(figB,'textbox',[0.335 0.932 0.52 0.030], ...
    'String',sprintf('Unanimously ordered pairs:  N=30, %d/36     N=50, %d/36     N=100, %d/36', ...
    unanimousCounts(1),unanimousCounts(2),unanimousCounts(3)), ...
    'EdgeColor','none', ...
    'HorizontalAlignment','center', ...
    'FontName','Arial', ...
    'FontSize',14.0, ...
    'Color',SUBINK);

hTrack = plot(axB,nan,nan,'-','Color',[0.65 0.72 0.76],'LineWidth',7.4);
h30 = plot(axB,nan,nan,'o', ...
    'MarkerSize',7.0, ...
    'MarkerFaceColor','w', ...
    'MarkerEdgeColor','k', ...
    'LineWidth',1.0);
h50 = plot(axB,nan,nan,'d', ...
    'MarkerSize',7.8, ...
    'MarkerFaceColor',HARM, ...
    'MarkerEdgeColor','k', ...
    'LineWidth',0.9);
h100 = plot(axB,nan,nan,'o', ...
    'MarkerSize',8.8, ...
    'MarkerFaceColor',NAVY, ...
    'MarkerEdgeColor','k', ...
    'LineWidth',0.9);

lgB = legend(axB,[hTrack h30 h50 h100], ...
    {'Range across N=30,50,100','N=30','N=50','N=100'}, ...
    'NumColumns',4, ...
    'Box','off', ...
    'FontName','Arial', ...
    'FontSize',12.0);

lgB.Position = [0.415 0.952 0.42 0.028];

save_panel_local(figB,output_dir,'Fig5_b');

%% =========================================================================
% PANEL c — effect separation + N=100 ranking consistency
%             (integrated alternative lollipop design)
% =========================================================================
rob100 = robustness(:,3);

idxHHLL = find(strcmp(pairLabels,'HH-LL'),1);

isHHLL = false(nPairs,1);
if ~isempty(idxHHLL)
    isHHLL(idxHHLL) = true;
end

isUnanimous100 = rob100 >= 1-1e-12;

% Sort rows by effect separation, largest first.
sortMatC = [-medianAbsEffect100(:), -rob100(:)];
[~,ordC] = sortrows(sortMatC,[1 2]);

pairLabelsC = pairLabels(ordC);
robC = rob100(ordC);
medAbsC = medianAbsEffect100(ordC);
isHHC = isHHLL(ordC);
isUniC = isUnanimous100(ordC);

positiveX = medAbsC(isfinite(medAbsC) & medAbsC > 0);

if isempty(positiveX)
    positiveX = 1;
end

xminC = max(min(positiveX)/1.8,1e-3);
xmaxC = max(positiveX)*1.55;

xEffect = medAbsC;
xEffect(~isfinite(xEffect) | xEffect <= 0) = xminC;

rowC = (1:nPairs)';

figC = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[100 35 1420 1120], ...
    'Name','Fig5_c', ...
    'NumberTitle','off');

set(figC,'Renderer','painters');

annotation(figC,'textbox',[0.018 0.952 0.035 0.035], ...
    'String','c', ...
    'EdgeColor','none', ...
    'FontName','Arial', ...
    'FontSize',30, ...
    'FontWeight','bold', ...
    'Color','k');

leftPosC  = [0.175 0.105 0.350 0.785];
rightPosC = [0.610 0.105 0.255 0.785];

% LEFT: effect separation
axCL = axes(figC,'Position',leftPosC);
hold(axCL,'on');

set(axCL, ...
    'XScale','log', ...
    'XLim',[xminC xmaxC], ...
    'YDir','reverse', ...
    'YLim',[0.35 nPairs+0.65], ...
    'YTick',rowC, ...
    'YTickLabel',pairLabelsC, ...
    'FontName','Arial', ...
    'FontSize',11.0, ...
    'LineWidth',1.0, ...
    'TickDir','out', ...
    'Box','off', ...
    'XColor',INK, ...
    'YColor',INK);

xlabel(axCL,'Absolute median pairwise effect difference (10^3 reported cases)', ...
    'FontSize',18, ...
    'Color',INK);

for r = 1:nPairs

    line(axCL,[xminC xmaxC],[r r], ...
        'Color',[0.92 0.93 0.94], ...
        'LineWidth',0.60, ...
        'HandleVisibility','off');

    if isHHC(r)
        cNow = BEST;
        lineW = 6.8;
        markerSize = 11.5;
    elseif isUniC(r)
        cNow = UNAN;
        lineW = 5.8;
        markerSize = 10.0;
    else
        cNow = OTHER;
        lineW = 4.8;
        markerSize = 8.7;
    end

    line(axCL,[xminC xEffect(r)],[r r], ...
        'Color',lighten_local(cNow,0.55), ...
        'LineWidth',lineW, ...
        'HandleVisibility','off');

    line(axCL,[xminC xEffect(r)],[r r], ...
        'Color','k', ...
        'LineWidth',0.85, ...
        'HandleVisibility','off');

    scatter(axCL,xEffect(r),r,markerSize^2, ...
        'MarkerFaceColor',cNow, ...
        'MarkerEdgeColor','k', ...
        'LineWidth',0.95, ...
        'HandleVisibility','off');

    if isHHC(r)
        scatter(axCL,xEffect(r),r,(markerSize+3)^2, ...
            'MarkerFaceColor','none', ...
            'MarkerEdgeColor','k', ...
            'LineWidth',1.35, ...
            'HandleVisibility','off');
    end
end

% RIGHT: ranking consistency
axCR = axes(figC,'Position',rightPosC);
hold(axCR,'on');

set(axCR, ...
    'XLim',[0.50 1.015], ...
    'YDir','reverse', ...
    'YLim',[0.35 nPairs+0.65], ...
    'YTick',rowC, ...
    'YTickLabel',repmat({''},nPairs,1), ...
    'XTick',[0.5 0.6 0.7 0.8 0.9 1.0], ...
    'FontName','Arial', ...
    'FontSize',11.0, ...
    'LineWidth',1.0, ...
    'TickDir','out', ...
    'Box','off', ...
    'XColor',INK, ...
    'YColor',INK);

xlabel(axCR,'Ranking consistency at N=100', ...
    'FontSize',18, ...
    'Color',INK);

patch(axCR, ...
    [0.95 1.015 1.015 0.95], ...
    [0.35 0.35 nPairs+0.65 nPairs+0.65], ...
    lighten_local(UNAN,0.82), ...
    'FaceAlpha',0.50, ...
    'EdgeColor','none', ...
    'HandleVisibility','off');

xline(axCR,0.95,'--','Color',[0.42 0.42 0.42],'LineWidth',1.0);
xline(axCR,1.00,'-','Color','k','LineWidth',1.15);

for r = 1:nPairs

    line(axCR,[0.50 1.00],[r r], ...
        'Color',[0.92 0.93 0.94], ...
        'LineWidth',0.60, ...
        'HandleVisibility','off');

    if isHHC(r)
        cNow = BEST;
        lineW = 6.8;
        markerSize = 11.5;
    elseif isUniC(r)
        cNow = UNAN;
        lineW = 5.8;
        markerSize = 10.0;
    else
        cNow = OTHER;
        lineW = 4.8;
        markerSize = 8.7;
    end

    line(axCR,[0.50 robC(r)],[r r], ...
        'Color',lighten_local(cNow,0.55), ...
        'LineWidth',lineW, ...
        'HandleVisibility','off');

    line(axCR,[0.50 robC(r)],[r r], ...
        'Color','k', ...
        'LineWidth',0.85, ...
        'HandleVisibility','off');

    scatter(axCR,robC(r),r,markerSize^2, ...
        'MarkerFaceColor',cNow, ...
        'MarkerEdgeColor','k', ...
        'LineWidth',0.95, ...
        'HandleVisibility','off');

    if isHHC(r)
        scatter(axCR,robC(r),r,(markerSize+3)^2, ...
            'MarkerFaceColor','none', ...
            'MarkerEdgeColor','k', ...
            'LineWidth',1.35, ...
            'HandleVisibility','off');
    end

    text(axCR,1.022,r,sprintf('%.2f',robC(r)), ...
        'HorizontalAlignment','left', ...
        'VerticalAlignment','middle', ...
        'FontName','Arial', ...
        'FontSize',10.5, ...
        'Color',SUBINK, ...
        'Clipping','off');
end

hOther = plot(axCR,nan,nan,'o', ...
    'MarkerSize',8.7, ...
    'MarkerFaceColor',OTHER, ...
    'MarkerEdgeColor','k', ...
    'LineWidth',0.95);

hUnan = plot(axCR,nan,nan,'o', ...
    'MarkerSize',10.0, ...
    'MarkerFaceColor',UNAN, ...
    'MarkerEdgeColor','k', ...
    'LineWidth',0.95);

hBest = plot(axCR,nan,nan,'o', ...
    'MarkerSize',11.5, ...
    'MarkerFaceColor',BEST, ...
    'MarkerEdgeColor','k', ...
    'LineWidth',1.0);

lgC = legend(axCR,[hOther hUnan hBest], ...
    {'Other pairs','N=100 unanimous','HH-LL'}, ...
    'NumColumns',3, ...
    'Box','off', ...
    'FontName','Arial', ...
    'FontSize',12.5);

lgC.Position = [0.305 0.875 0.41 0.045];

annotation(figC,'textbox',[0.535 0.855 0.29 0.055], ...
    'String',sprintf('Unanimous pairs at N=100: %d/36\nHH-LL is unanimous and ranks 2/36 by median separation.', ...
    unanimousCounts(3)), ...
    'EdgeColor','none', ...
    'HorizontalAlignment','center', ...
    'FontName','Arial', ...
    'FontSize',12.2, ...
    'Color',SUBINK);

save_panel_local(figC,output_dir,'Fig5_c');

%% =========================================================================
% PANEL d — nested-ensemble sensitivity
% =========================================================================
figD = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[150 90 1200 860], ...
    'Name','Fig5_d', ...
    'NumberTitle','off');

set(figD,'Renderer','painters');

annotation(figD,'textbox',[0.020 0.945 0.040 0.040], ...
    'String','d', ...
    'EdgeColor','none', ...
    'FontName','Arial', ...
    'FontSize',30, ...
    'FontWeight','bold', ...
    'Color','k');

axD = axes(figD,'Position',[0.105 0.150 0.820 0.690]);
hold(axD,'on');

set(axD, ...
    'XLim',[28 112], ...
    'XTick',sizes, ...
    'YLim',[0 1.04], ...
    'YTick',[0 0.25 0.50 0.75 1.00], ...
    'FontName','Arial', ...
    'FontSize',17.0, ...
    'LineWidth',1.0, ...
    'TickDir','out', ...
    'Box','off', ...
    'XColor',INK, ...
    'YColor',INK);

xlabel(axD,'Nested ensemble size', ...
    'FontSize',19.0, ...
    'Color',INK);

ylabel(axD,'Criterion fraction', ...
    'FontSize',19.0, ...
    'Color',INK);

for yy = [0 0.5 1.0]
    yline(axD,yy,':','Color',GRIDC,'LineWidth',0.9);
end

critCols = [ ...
    NAVY; ...
    HARM; ...
    TEAL; ...
    SLATE];

critMarks = {'o','s','^','d'};
labelYoff = [0.030 0.000 -0.010 -0.020];

for m = 1:4

    yv = criterionFrac(m,:);

    plot(axD,sizes,yv,'-','Color','k','LineWidth',2.8);
    plot(axD,sizes,yv,'-','Color',critCols(m,:),'LineWidth',2.0);

    for kk = 1:3

        plot(axD,sizes(kk),yv(kk),critMarks{m}, ...
            'MarkerSize',9.0, ...
            'MarkerFaceColor',critCols(m,:), ...
            'MarkerEdgeColor','k', ...
            'LineWidth',0.9);

        text(axD,sizes(kk),min(1.03,yv(kk)+0.032),sprintf('%.2f',yv(kk)), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','bottom', ...
            'FontName','Arial', ...
            'FontSize',12.0, ...
            'Color',SUBINK);
    end

    text(axD,104,yv(end)+labelYoff(m), ...
        sprintf('%s   %.2f',criterionNames{m},yv(end)), ...
        'HorizontalAlignment','left', ...
        'VerticalAlignment','middle', ...
        'FontName','Arial', ...
        'FontSize',15.0, ...
        'FontWeight','bold', ...
        'Color',critCols(m,:));
end

annotation(figD,'textbox',[0.16 0.065 0.68 0.030], ...
    'String','Fractions describe the constructed admissible ensemble; they are not posterior probabilities.', ...
    'EdgeColor','none', ...
    'HorizontalAlignment','center', ...
    'FontName','Arial', ...
    'FontSize',13.0, ...
    'Color',SUBINK);

save_panel_local(figD,output_dir,'Fig5_d');

fprintf('\nCorrected Fig. 5 panels saved to:\n%s\n',output_dir);
fprintf('Integrity check passed: unanimous pairs = 6/36, 6/36, 4/36.\n');
fprintf('Integrity check passed: HH > LL = 30/30, 50/50, 100/100.\n');

%% =========================================================================
% Local functions
% =========================================================================
function R = pairwise_total_reported_local(values)

nStrategies = size(values,2);

E = squeeze(values(:,:,1,5));

R = zeros(nStrategies,nStrategies);

for i = 1:nStrategies
    for j = 1:nStrategies

        if i == j
            R(i,j) = 0;
        else
            R(i,j) = mean(E(:,i) > E(:,j));
        end
    end
end
end


function n = count_unanimous_pairs_local(R)

nStrategies = size(R,1);

n = 0;

for i = 1:(nStrategies-1)
    for j = (i+1):nStrategies

        p = R(i,j);

        if p <= 1e-12 || p >= 1-1e-12
            n = n + 1;
        end
    end
end
end


function labels = unanimous_pair_labels_local(R,strategyNames)

nStrategies = size(R,1);

labels = {};

for i = 1:(nStrategies-1)
    for j = (i+1):nStrategies

        p = R(i,j);

        if p <= 1e-12 || p >= 1-1e-12
            labels{end+1} = [strategyNames{i} '-' strategyNames{j}]; %#ok<AGROW>
        end
    end
end
end


function save_panel_local(fig,output_dir,name)

figFile = fullfile(output_dir,[name '.fig']);
pngFile = fullfile(output_dir,[name '.png']);

savefig(fig,figFile);

if exist(pngFile,'file')
    try
        delete(pngFile);
    catch
        pngFile = fullfile(output_dir, ...
            [name '_' datestr(now,'yyyymmdd_HHMMSS') '.png']);
    end
end

try
    exportgraphics(fig,pngFile, ...
        'Resolution',600, ...
        'BackgroundColor','white');
catch ME
    warning('exportgraphics failed for %s: %s. Falling back to print().', ...
        name,ME.message);

    print(fig,pngFile,'-dpng','-r600');
end
end


function c = darken_local(c0,amount)

amount = max(0,min(1,amount));
c = c0.*(1-amount);
c = min(max(c,0),1);
end


function c = lighten_local(c0,amount)

amount = max(0,min(1,amount));
c = c0 + (1-c0).*amount;
c = min(max(c,0),1);
end
